//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assimilated.DMVRU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assimilated.DMVRU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{0}&apos; argument. {1}{2}Type dmvru -help to see full list of arguments..
        /// </summary>
        internal static string ErrorInArgument {
            get {
                return ResourceManager.GetString("ErrorInArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RewriteEngine On
        ///RewriteBase /
        ///# The next code line is currently commented out on purpose so it will be ignored.
        ///# It is only for testing the code when you don&apos;t really want to close the site.
        ///# It closes the site ONLY to you, but leaves it OPEN to everybody else.
        ///# When commented out, the site is closed to everyone, including yourself.
        ///# To enable the line, remove the # (pound sign) at the start of it. 
        ///# You MUST first change the digits 111 222 333 444 to match YOUR IP address.
        ///#RewriteCond %{REMO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTAccessFile {
            get {
                return ResourceManager.GetString("HTAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///    header(&apos;HTTP/1.1 503 Service Temporarily Unavailable&apos;,true,503);
        ///    header(&apos;Status: 503 Service Temporarily Unavailable&apos;);
        ///    header(&apos;Retry-After: 300&apos;);
        ///?&gt;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;noindex,nofollow&quot;&gt;
        ///    &lt;title&gt;503 - Temporarily Down for Maintenance&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            width: 400px;
        ///            margin: 0 auto;
        ///            tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaintenancePage {
            get {
                return ResourceManager.GetString("MaintenancePage", resourceCulture);
            }
        }
    }
}
